FROM node:22-bookworm-slim AS build
WORKDIR /app
ARG VITE_BACKEND_API_URL=/api
ARG VITE_PUBLIC_SITE_URL
ARG VITE_RTMP_PUBLISH_HOST
ARG VITE_DEFAULT_COVER_IMAGE_URL
ARG VITE_DEFAULT_PROFILE_IMAGE_URL
ARG VITE_TURNSTILE_SITE_KEY
ENV VITE_BACKEND_API_URL=${VITE_BACKEND_API_URL} \
    VITE_PUBLIC_SITE_URL=${VITE_PUBLIC_SITE_URL} \
    VITE_RTMP_PUBLISH_HOST=${VITE_RTMP_PUBLISH_HOST} \
    VITE_DEFAULT_COVER_IMAGE_URL=${VITE_DEFAULT_COVER_IMAGE_URL} \
    VITE_DEFAULT_PROFILE_IMAGE_URL=${VITE_DEFAULT_PROFILE_IMAGE_URL} \
    VITE_TURNSTILE_SITE_KEY=${VITE_TURNSTILE_SITE_KEY}
COPY package.json package-lock.json* ./
RUN npm ci
COPY . .
RUN npm run build

FROM caddy:2.9-alpine
COPY --from=build /app/dist /srv
COPY Caddyfile /etc/caddy/Caddyfile
